# Copyright 2019 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

dist: xenial
language: python
python: 3.7.2

addons:
  sonarcloud:
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

script: 
  - ./lint.sh && ./test.sh
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "ibm/qpylib"]; then sonar-scanner; fi # sonar only on non-PRs

after_success:
  - if [[ $TRAVIS_TAG ]]; then
      ./build.sh ${TRAVIS_TAG};
    else
      ./build.sh "0.0.dev${TRAVIS_BUILD_NUMBER}";
    fi

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: dist/qpylib-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
